### ISSUE TITLE
Causes issues with 3D resource packs

### ISSUE THREAD

**Issue by MeeniMc** [Rynnavinx/sodium-shadowy-path-blocks#1]
The inside of 3D blocks from 3D resource packs (e.g., 3D bookshelves from Vanilla Tweaks, UltimaCraft Models, etc) get all dark and weird.

**Comment by Rynnavinx** [comment]
It seems like this is actually primarily a Sodium issue. Some things, like the 3D bookshelves, appear to be fixed with this mod removed, but others, like UltimaCraft's hay bales and jack o'lanterns, seem be be darkened with or without this mod, only being fixed when I removed Sodium. And even the 3D bookshelves are darkened with Sodium if smooth lighting is off.

**Comment by MeeniMc** [comment]
I think the only relevant case is for non-emissive blocks, like bookshelves. Because you are right, the other cases are probably due to some other unrelated bugs.

The issue with Sodium and emissive blocks with 3D extrusions (e.g., jack-o-lantern, furnace...) has been present for a very long time, see https://github.com/CaffeineMC/sodium-fabric/issues/226. 

I have noticed the hay bales as well though, not sure what's the reason for that, it could be a bug in the pack itself, or the way the texture is mapped on the model. Anyway probably not something this mod should do something about. 

Cheers!
