### ISSUE TITLE
Incompatibility with Continuity alpha 1.19.3

### ISSUE THREAD

**Issue by booky10** [Rynnavinx/sodium-shadowy-path-blocks#11]
After installing Continuity's alpha version for 1.19.3 (and enabling its default connected texture resourcepack) SSPB stops working.
This issue can be worked around by setting `ambient-occlusion-mode` to `hybrid` in the indium configuration.

This bug can be reproduced with Continuity, Fabric API, Indium, Sodium and SSPB.
[Download link for Continuity alpha 1.19.3](https://cdn.discordapp.com/attachments/872543494554648637/1062469061100982313/continuity-3.0.0-alpha.21.19.3.jar)

Additional info provided by Continuity's author:
![image](https://user-images.githubusercontent.com/53302036/211905186-b7e2137e-5876-4afe-8e78-ac1ead9e69eb.png)

**Comment by Rynnavinx** [comment]
Yes, this is the same incompatibility with LambdaBetterGrass that was mentioned on CF and Modrinth. I suppose I should have just been more general and said that it was an Indium rendering incompatibility, rather than just saying it was incompatible with a single mod.

I've thought about adding a new feature that would also address this, but for now, just keep using hybrid mode.
