### ISSUE TITLE
Menu options not working as expected with CTM mods

### ISSUE THREAD

**Issue by ItsRodrigoAl** [Rynnavinx/sodium-shadowy-path-blocks#25]
## The problems
I use a connected textures mod and it is a bit confusing because:
- It shows the last option "Use vanilla lighting for path blocks" disabled, so anyone could think "ah well, then I can't use this option because is disabled by default and it seems I can't enable it", but actually that option is disabled because is **enabled** by default with CTM mods? Confusing
- The "Shadowyness" slider, being the first option, won't work neither because the last option is enabled, confusing again
- And the second option "Only affect path blocks" doesn't even work? No matter if I disable or enable it, it won't add or remove the shadow to other blocks like farm, this will be always for path blocks

### Current options
![2024-04-29_12 33 57](https://github.com/Rynnavinx/sodium-shadowy-path-blocks/assets/57012631/5954e40e-4a3e-4169-a47b-69c6db11cc60)

## Questions/Suggestions 
- Is not possible to also disable the "Shadowyness" slider if the "Use vanilla lighting for path blocks" option is disabled?
- Is not possible to show the "Use vanilla lighting" option enabled? Because it marks it with an in-line thing as it were not possible to enable it, but actually is enabled by default
- Also, wouldn't be better to re-order the options to be like this:
  - 1 "Use vanilla lighting for path blocks", because is the main option to change the kind of shadow and also the slider option is affected by this
  - 2 "Shadowyness", because you change the level of shadow depending of the previous option
  - 3 "Only affect path blocks", because is just an extra option to enable/disable it after the main options

### My suggestion
![image](https://github.com/Rynnavinx/sodium-shadowy-path-blocks/assets/57012631/63dc3f50-afa0-4f61-8ad3-7fff7587cde4)

**Comment by Rynnavinx** [comment]
I don't disable the Shadowyness slider because it should still affect other blocks, even when Use vanilla lighting for path blocks is on. As long as those other blocks aren't using modded rendering, anyways. There's an argument to be made for disabling this when the other two options are both on, but I'll get more into that later.

If the Only affect path blocks option doesn't affect other blocks, again, could the blocks you're looking at also be using modded rendering? It toggles the stronger shadows on blocks like farmland and slabs for me, as long as those blocks aren't using modded rendering. Or does it just not do anything ever, because I've never seen an issue with that.

As for showing the vanilla lighting as off when the option is disabled, yeah it is kinda confusing at first glance. I used sodium's option menu code to make these options and I believe it just shows as off whenever an option is disabled. And as for disabling/enabling the shadowyness slider when the other two options are both on or not, you'd have to exit and re-enter the options menu for the effect to show, which is clunky and probably worse than just not disabling it. May or may not have to modify the options area of sodium to make these two things work. Might be worth it, but not totally sure yet.

**Comment by ItsRodrigoAl** [comment]
Hey, an update of the issue: I've just noticed all those options changes when using a texture pack, not by just having a mod for CTM support

I mean, I use the Continuity mod, and without any texture pack, I can enable and disable all the options as expected (the shadow slider, the only affect path blocks and the vanilla lighting), **however** when using any texture pack with CTM it shows the "Use vanilla lighting" as no selectable (enabled), so the Shadowyness slider is ignored, however the "Only affect path blocks" stops working no matter if I can enable or disable it

**Comment by Rynnavinx** [comment]
Issues are addressed in 7f5b76a, with release 3.4.0

1. "Use vanilla lighting for path blocks" actually being enabled when the option shows disabled: You can now toggle it when modded rendering is used. This means it is never forced on, so it will always actually be disabled when it shows as disabled.
2. "Shadowyness" slider seemingly being ignored when "Use vanilla lighting for path blocks" is enabled: Continuity makes **ALL** blocks use modded rendering when a CTM resource pack is used, and shadowyness didn't affect blocks with modded rendering, so this was the actual cause of the slider not doing anything. It just so happened that "Use vanilla lighting for path blocks" was force enabled for the same reason. Shadowyness now affects blocks with modded rendering, so this issue is fixed.
(Note that this option still does not affect path blocks when "Use vanilla lighting for path blocks" is enabled, but that is stated in the tooltips and is supposed to be like that)
3. "Only affect path blocks" not working: The issue and fix were the same as the one above. If this option enables/disables shadowyness for certain blocks, but shadowyness doesn't work on **ANY** block when a CTM pack is used, then this option wouldn't do anything. Since shadowyness now works on blocks with modded rendering, this issue is fixed too.

As much of the confusion should be cleared up with these fixes, I won't be reordering the options. And I'm also not disabling the shadowyness slider when the other two options are enabled, because of the reasons stated before.
