### ISSUE TITLE
in 1.21, the pathblocks are fine but stuff like wall blocks do not have the shadowiness

### ISSUE THREAD

**Issue by username89213712** [Rynnavinx/sodium-shadowy-path-blocks#28]
in 1.21
![2024-07-03_19 02 23](https://github.com/Rynnavinx/sodium-shadowy-path-blocks/assets/98259518/fefdfe8e-b052-460b-857f-7a276996aa71)
in 1.20.1
![Screenshot 2024-07-03 190514](https://github.com/Rynnavinx/sodium-shadowy-path-blocks/assets/98259518/9cc41b63-c902-44a1-b49a-cee18ba655d5)

**Comment by Rynnavinx** [comment]
By any chance, was the "Only affect path blocks" option on when you were playing 1.21? Or do you maybe have other mods installed?

For me, a wall like that in 1.21 looks the same as how your 1.20.1 screenshot looks, so I personally am not able to recreate the issue.

**Comment by username89213712** [comment]
> ffec

idk how to turn it on or off since there's no options in the mod menu mod, sorry for the late reply

**Comment by username89213712** [comment]
where is the only affect path blocks option?

**Comment by Rynnavinx** [comment]
Options --> Video Settings --> SSPB

**Comment by username89213712** [comment]
okay, thanks, I tried that out but it didn't work, but I finally figured out what was wrong, for some reason the mod indium is the issue, getting rid of it fixed it

**Comment by username89213712** [comment]
so turns out, the game crashes with any piston movement and some mods don't work without indium, is there any reason the mod is not compatible with indium?

**Comment by Rynnavinx** [comment]
The piston crash is likely not an issue with this mod (I even tested it just in case). 
As for the lighting issue, what other mods and resource packs are you using? Because this mod should work fine with indium.

**Comment by username89213712** [comment]
as for mods I'm using:
1. accurate block placement
2. bobby 
3. capes
4. continuity
5. eating animations
6. fabric api
7. freecam
8. gamma utils
9. indium
10. iris
11. lithium
12. logical zoom
13. modmenu
14. shulkerbox tooltips
15. skinlayers 3D
16. sodiumm
17. SSPB
18. sound physics remastered
19. world edit

and for resource packs:

1. glass pane culling fix and default connected textures cus of continuity
2. vanilla tweaks
3. high contrast UI

**Comment by Rynnavinx** [comment]
Seems to have to do with Continuity. Seems that mod starting from v3.0.0 forces every block to use indium if even a single connected texture is present. This basically means all blocks bypass this mod, so SSPB doesn't do anything but set path blocks to use the vanilla lighting algorithm in indium. If this is what's causing the issue for you, then its related to #25.

A partial workaround for now would be to go to .minecraft/config/indium-renderer.properties and change "ambient-occlusion-mode=auto" to "ambient-occlusion-mode=hybrid" or "ambient-occlusion-mode=vanilla". Note that this is only a partial workaround because SSPB options still won't affect anything in this scenario.

**Comment by Rynnavinx** [comment]
Actually, @username89213712, if it's not too much to ask, could you disable all your resource packs and tell me if that fixes the issue? With the set of mods and resource packs you posted, the resource packs were the issue for me. It probably also is the issue on your end, but confirmation wouldn't hurt.

**Comment by Rynnavinx** [comment]
Under the testing I did with your mods and resource packs, I'm pretty confident this issue is solved in 7f5b76a, with release 3.4.0. If you're still having this issue, feel free to reopen.

Remember to set "ambient-occlusion-mode" back to "auto" in indium-renderer.properties if you changed it to "hybrid" or "vanilla" previously.
