### ISSUE TITLE
Sodium 0.6 Support

### ISSUE THREAD

**Issue by LobbyLC** [Rynnavinx/sodium-shadowy-path-blocks#33]
I hate to be the one to ask, but out of interest, are there plans for Sodium Shadowy Path Blocks to support Sodium's recent update? The mod unfortunately appears to be incompatible as of right now.

Edit: Only after posting this did I notice the "Now explicitly incompatible with Sodium 0.6.0 versions" note in the most recent changelog, but I'm still confused as to whether that means it's staying that way, or if that change was made due to an issue, and a new release will be published in the future to support them. I know this doesn't really justify creating an issue, but if you could clarify, it'd mean a lot!

**Comment by adamiola** [comment]
yes pls

**Comment by Rynnavinx** [comment]
Ah, sorry if the incompatibility note was confusing. It just meant that SSPB v3.4.0 would tell you that the versions are incompatible and would not load the game, rather than trying to load and then crash.

But yes, I'd been working on SSPB v4 recently, which supports Sodium v0.6.0 on both Fabric and NeoForge, and it's just been released!
